- hosts: localhost
  tasks:
  
    - name: Publish kube cluster event.
      kube_cluster_event:
        authorization: "{{ authorization }}"
        account_alias: "{{ account_alias }}"
        cluster_id: "{{ cluster_id }}"
        message: "Starting node provisioning operations."
  
    - name: Generate server root password
      command: openssl rand -base64 15
      register: server_pass
    
    - name: Set server password fact.
      set_fact:
        server_pass: "{{ server_pass.stdout }}"
    
    - name: Create new kubernetes server for node deployment.
      clc_server:
        name: "{{ name }}"
        location: "{{ datacenter }}"
        template: ubuntu-14-64
        password: "{{ server_pass }}"
        count: 1
        group: "{{ group }}"
        network_id: "{{ network_id }}"
        cpu: 4
        memory: 8
        type: standard
        storage_type: standard
      register: new_inv
    
    - name: Add new servers to in-memory inventory.
      add_host:
        name={{ item.name }}
        ansible_ssh_host={{ item.ipaddress }}
        ansible_ssh_user=root
        ansible_ssh_pass={{ server_pass }}
        etcd_endpoint=http://{{ master_ip }}:4001 
        apiserver_endpoint=http://{{ master_ip }}:8080
        groups=node
      with_items: new_inv.servers

    - name: Set playbook facts.
      set_fact:
        node_ip: "{{ item.ipaddress }}"
      with_items: new_inv.servers

    - name: Update node configuration document.
      kube_cluster_node_patch:
        authorization: "{{ authorization }}"
        account_alias: "{{ account_alias }}"
        cluster_id: "{{ cluster_id }}"
        node_id: "{{ node_id }}"
        patch:
          node_ip: "{{ node_ip }}"
          node_ssh_user: "root"
          node_ssh_pass: "{{ server_pass }}"

    - name: Publish kube cluster event.
      kube_cluster_event:
        authorization: "{{ authorization }}"
        account_alias: "{{ account_alias }}"
        cluster_id: "{{ cluster_id }}"
        message: "Node instance created."

    - name: Wait for SSH services be vailable on hosts.
      command: sleep 30

- include: kubernetes-node.yml hosts=node