- hosts: localhost
  tasks:
  
    - name: Publish kube cluster event.
      kube_cluster_event:
        endpoint: "{{ services_endpoint }}"
        authorization: "{{ authorization }}"
        account_alias: "{{ account_alias }}"
        cluster_id: "{{ cluster_id }}"
        message: "Starting cluster provisioning operations."
  
    - name: Generate server root password.
      command: openssl rand -base64 15
      register: server_pass
    
    - name: Set server password fact.
      set_fact:
        server_pass: "{{ server_pass.stdout }}"
    
    - name: Create group if needed.
      clc_group:
        name: "{{ group }}"
        location: "{{ datacenter }}"
        state: present
    
    - name: Create new kubernetes server for master deployment.
      clc_server:
        name: "K8SM"
        location: "{{ datacenter }}"
        template: ubuntu-14-64
        password: "{{ server_pass }}"
        count: 1
        group: "{{ group }}"
        network_id: "{{ network_id }}"
        cpu: 1
        memory: 2
        type: standard
        storage_type: standard
      register: new_inv_master
      
    - name: Add new servers to in-memory inventory.
      add_host:
        name={{ item.name }}
        ansible_ssh_host={{ item.ipaddress }}
        ansible_ssh_user=root
        ansible_ssh_pass={{ server_pass }}
        etcd_endpoint=http://{{ item.ipaddress }}:4001 
        apiserver_endpoint=http://{{ item.ipaddress }}:8080
        groups=master
      with_items: new_inv_master.servers
      
    - name: Set playbook facts.
      set_fact:
        master_ip: "{{ item.ipaddress }}"
      with_items: new_inv_master.servers

    - name: Update the stored cluster configuration.
      kube_cluster_patch:
        endpoint: "{{ services_endpoint }}"
        authorization: "{{ authorization }}"
        account_alias: "{{ account_alias }}"
        cluster_id: "{{ cluster_id }}"
        patch:
          master_ip: "{{ master_ip }}"
          master_ssh_user: "root"
          master_ssh_pass: "{{ server_pass }}"
      
    - name: Publish kube cluster event.
      kube_cluster_event:
        endpoint: "{{ services_endpoint }}"
        authorization: "{{ authorization }}"
        account_alias: "{{ account_alias }}"
        cluster_id: "{{ cluster_id }}"
        message: "Master server instance created with IP {{ master_ip }}"
      
    - debug: msg="{{ master_ip }}"
    
    - name: Create new kubernetes server for node deployment.
      clc_server:
        name: "K8SN"
        location: "{{ datacenter }}"
        template: ubuntu-14-64
        password: "{{ server_pass }}"
        count: 1
        group: "{{ group }}"
        network_id: "{{ network_id }}"
        cpu: 4
        memory: 8
        type: standard
        storage_type: standard
      register: new_inv_node
    
    - name: Add new servers to in-memory inventory.
      add_host:
        name={{ item.name }}
        ansible_ssh_host={{ item.ipaddress }}
        ansible_ssh_user=root
        ansible_ssh_pass={{ server_pass }}
        etcd_endpoint=http://{{ master_ip }}:4001 
        apiserver_endpoint=http://{{ master_ip }}:8080
        groups=node
      with_items: new_inv_node.servers
      
    - name: Create node configuration documents.
      kube_cluster_node_create:
        endpoint: "{{ services_endpoint }}"
        authorization: "{{ authorization }}"
        account_alias: "{{ account_alias }}"
        cluster_id: "{{ cluster_id }}"
        data:
          name: "{{ item.name }}"
          node_ip: "{{ item.ipaddress }}"
          node_ssh_user: "root"
          node_ssh_pass: "{{ server_pass }}"
      with_items: new_inv_node.servers
      
    - name: Publish kube cluster event.
      kube_cluster_event:
        endpoint: "{{ services_endpoint }}"
        authorization: "{{ authorization }}"
        account_alias: "{{ account_alias }}"
        cluster_id: "{{ cluster_id }}"
        message: "Node server instance created with IP {{ item.ipaddress }}."
      with_items: new_inv_node.servers
    
    - name: Wait for SSH services be vailable on hosts.
      command: sleep 30

- include: kubernetes-master.yml
- include: kubernetes-node.yml

- hosts: master
  tasks:
  - name: Create Replication Controller - cluster dns
    kubernetes:
      endpoint: "{{ apiserver_endpoint }}"
      state: present
      model:
        apiVersion: v1
        kind: ReplicationController
        metadata:
          name: dns-rc
          namespace: default
        spec:
          replicas: 1
          imagePullPolicy: IfNotPresent
          selector:
            app: dns
          template:
            metadata:
              labels:
                app: dns
            spec:
              containers:
              - name: etcd
                image: quay.io/coreos/etcd:v2.2.2
                args:
                - -listen-client-urls
                - http://0.0.0.0:2379,http://0.0.0.0:4001
                - -advertise-client-urls 
                - http://127.0.0.0:2379,http://127.0.0.1:4001
              - name: skydns
                image: skynetservices/skydns:2.5.3a
                args:
                - -addr=0.0.0.0:53
                - -hostmaster=mark.ramach@ctl.io
                - -machines=http://127.0.0.1:4001
                - -rcache=0
                - -rcache-ttl=0
                - -verbose=true
              - name: kube2sky
                image: markramach/kube2sky:latest
            restartPolicy: Always
  
  - name: Create Service With Node Port - cluster dns
    kubernetes:
      endpoint: "{{ apiserver_endpoint }}"
      state: present
      model:
        apiVersion: v1
        kind: Service
        metadata:
          name: dns
          namespace: default
          labels:
            app: dns
        spec:
          type: NodePort
          ports:
          - port: 53
            targetPort: 53
            protocol: UDP
            nodePort: 30053
          clusterIP: 192.168.253.2
          selector:
            app: dns