- hosts: all
  tasks:
  
#  - name: Publish kube cluster event.
#    kube_cluster_event:
#      authorization: "{{ authorization }}"
#      account_alias: "{{ account_alias }}"
#      cluster_id: "{{ cluster_id }}"
#      message: "Starting {{ application_name }} deployment."  
  
  - name: Create Ghost Replication Controller.
    kubernetes:
      endpoint: "{{ apiserver_endpoint }}"
      state: present
      model:
        apiVersion: v1
        kind: ReplicationController
        metadata:
          name: "{{ application_name }}-rc"
          namespace: default
        spec:
          replicas: 1
          imagePullPolicy: IfNotPresent
          selector:
            app: "{{ application_name }}"
          template:
            metadata:
              labels:
                app: "{{ application_name }}"
            spec:
              containers:
              - name: "ghost"
                image: ghost
                ports:
                - containerPort: 2368
            restartPolicy: Always
            
#  - name: Publish kube cluster event.
#    kube_cluster_event:
#      authorization: "{{ authorization }}"
#      account_alias: "{{ account_alias }}"
#      cluster_id: "{{ cluster_id }}"
#      message: "{{ application_name }} replication controller created."
            
  - name: Create Ghost Service
    kubernetes:
      endpoint: "{{ apiserver_endpoint }}"
      state: present
      model:
        apiVersion: v1
        kind: Service
        metadata:
          name: "{{ application_name }}-svc"
          namespace: default
          labels:
            app: "{{ application_name }}"
        spec:
          type: NodePort
          ports:
          - port: 8080
            targetPort: 2368
            protocol: TCP
          selector:
            app: "{{ application_name }}"
    register: service_resp
            
  - debug: msg={{ service_resp }}
            
#  - name: Publish kube cluster event.
#    kube_cluster_event:
#      authorization: "{{ authorization }}"
#      account_alias: "{{ account_alias }}"
#      cluster_id: "{{ cluster_id }}"
#      message: "{{ application_name }} service created."