- hosts: localhost
  connection: local
  tasks:
  - name: Publish kube cluster event.
    kube_cluster_event:
      authorization: "{{ authorization }}"
      account_alias: "{{ account_alias }}"
      cluster_id: "{{ cluster_id }}"
      message: "Deleting {{ application_name }}."  
  
- hosts: all  
  tasks:
  - name: Ensure pip is installed
    apt: name=python-pip state=present
      
  - name: Update Requests Version
    pip: name=requests state=latest
    
  - name: Update pip Version
    pip: name=pip state=latest
  
  - name: Scale Up Job Pods
    kubernetes-scale:
      endpoint: "{{ apiserver_endpoint }}"
      name: "{{ application_name }}-rc"
      namespace: default
      replicas: 0
      
  - name: Remove Replication Controller.
    kubernetes:
      endpoint: "{{ apiserver_endpoint }}"
      state: absent
      model:
        apiVersion: v1
        kind: ReplicationController
        metadata:
          name: "{{ application_name }}-rc"
          namespace: default
      
- hosts: localhost
  connection: local
  tasks:    
  - name: Publish kube cluster event.
    kube_cluster_event:
      authorization: "{{ authorization }}"
      account_alias: "{{ account_alias }}"
      cluster_id: "{{ cluster_id }}"
      message: "{{ application_name }} replication controller deleted."

- hosts: all  
  tasks:            
  - name: Delete Service
    kubernetes:
      endpoint: "{{ apiserver_endpoint }}"
      state: absent
      model:
        apiVersion: v1
        kind: Service
        metadata:
          name: "{{ application_name }}-svc"
          namespace: default
          labels:
            app: "{{ application_name }}"

- hosts: localhost
  connection: local
  tasks:            
  - name: Publish kube cluster event.
    kube_cluster_event:
      authorization: "{{ authorization }}"
      account_alias: "{{ account_alias }}"
      cluster_id: "{{ cluster_id }}"
      message: "{{ application_name }} service deleted."