- hosts: localhost
  connection: local
  tasks:
  - name: Publish kube cluster event.
    kube_cluster_event:
      authorization: "{{ authorization }}"
      account_alias: "{{ account_alias }}"
      cluster_id: "{{ cluster_id }}"
      message: "Starting {{ application_name }} deployment."

  - name: Fetch storage configuration.
    kube_cluster_storage_get:
      authorization: "{{ authorization }}"
      account_alias: "{{ account_alias }}"
      cluster_id: "{{ cluster_id }}"
      storage_id: "{{ storage_id }}"
    register: storage
      
  - name: Add gcfs server to in-memory inventory.
    add_host:
      name={{ storage.content.name }}
      ansible_ssh_host={{ storage.content.storage_ip }}
      ansible_ssh_user={{ storage.content.storage_ssh_user }}
      ansible_ssh_pass={{ storage.content.storage_ssh_pass }}
      gcfs_ip={{ storage.content.storage_ip }}
      volume_name={{ application_name }}
      volume_path=/{{ application_name }}
      groups=gcfs
      
  - name: Publish kube cluster event.
    kube_cluster_event:
      authorization: "{{ authorization }}"
      account_alias: "{{ account_alias }}"
      cluster_id: "{{ cluster_id }}"
      message: "Storage volume created for {{ application_name }}."
      
- hosts: gcfs
  roles:
    - gluster-volume
    
- hosts: "all:!gcfs" 
  tasks:
  - name: Fetch storage configuration.
    kube_cluster_storage_get:
      authorization: "{{ authorization }}"
      account_alias: "{{ account_alias }}"
      cluster_id: "{{ cluster_id }}"
      storage_id: "{{ storage_id }}"
    register: storage
  
  - name: Create GCFS Endpoint
    kubernetes:
      endpoint: "{{ apiserver_endpoint }}"
      state: present
      model:
        apiVersion: v1
        kind: Endpoints
        metadata:
          name: "{{ application_name }}"
          namespace: default
        subsets:
          - addresses:
            - ip: "{{ storage.content.storage_ip }}"
            ports:
            - port: 24007

  - name: Create mysql Replication Controller.
    kubernetes:
      endpoint: "{{ apiserver_endpoint }}"
      state: present
      model:
        apiVersion: v1
        kind: ReplicationController
        metadata:
          name: "{{ application_name }}-rc"
          namespace: default
        spec:
          replicas: 1
          imagePullPolicy: IfNotPresent
          selector:
            app: "{{ application_name }}"
          template:
            metadata:
              labels:
                app: "{{ application_name }}"
            spec:
              volumes:
              - name: msql-volume
                glusterfs:
                  endpoints: "{{ application_name }}"
                  path: "{{ application_name }}"
                  readOnly: false
              containers:
              - name: "mysql"
                image: mysql
                volumeMounts:
                - mountPath: "/var/lib/mysql"
                  name: "{{ application_name }}"
                env:
                - name: MYSQL_ROOT_PASSWORD
                  value: password
                ports:
                - containerPort: 3306
            restartPolicy: Always

- hosts: localhost
  connection: local
  tasks:
  - name: Publish kube cluster event.
    kube_cluster_event:
      authorization: "{{ authorization }}"
      account_alias: "{{ account_alias }}"
      cluster_id: "{{ cluster_id }}"
      message: "{{ application_name }} replication controller created."

- hosts: "all:!gcfs"  
  tasks: 
  - name: Create mysql Service
    kubernetes:
      endpoint: "{{ apiserver_endpoint }}"
      state: present
      model:
        apiVersion: v1
        kind: Service
        metadata:
          name: "{{ application_name }}-svc"
          namespace: default
          labels:
            app: "{{ application_name }}"
        spec:
          type: NodePort
          ports:
          - port: 3306
            targetPort: 3306
            protocol: TCP
            nodePort: 30306
          selector:
            app: "{{ application_name }}"
    register: service_resp

- hosts: localhost
  connection: local
  tasks:
  - name: Publish kube cluster event.
    kube_cluster_event:
      authorization: "{{ authorization }}"
      account_alias: "{{ account_alias }}"
      cluster_id: "{{ cluster_id }}"
      message: "{{ application_name }} service created."