- hosts: all
  tasks:
  - name: Update the stored cluster app configuration.
    kube_cluster_app_patch:
      endpoint: "{{ services_endpoint }}"
      authorization: "{{ authorization }}"
      account_alias: "{{ account_alias }}"
      cluster_id: "{{ cluster_id }}"
      cluster_app_id: "{{ cluster_app_id }}"
      patch:
        state: "install"
        installation: 20

  - name: Create Drupal Replication Controller.
    kubernetes:
      endpoint: "{{ apiserver_endpoint }}"
      state: present
      model:
        apiVersion: v1
        kind: ReplicationController
        metadata:
          name: "{{ application_name }}-rc"
          namespace: default
        spec:
          replicas: 1
          imagePullPolicy: IfNotPresent
          selector:
            app: "{{ application_name }}"
          template:
            metadata:
              labels:
                app: "{{ application_name }}"
            spec:
              containers:
              - name: "mariadb"
                image: mariadb:5
                env:
                - name: MYSQL_ROOT_PASSWORD
                  value: password
                - name: MYSQL_DATABASE
                  value: drupal
                ports:
                - containerPort: 3306
              - name: "drupal"
                image: drupal:8.0.1
                env:
                - name: MYSQL_PORT_3306_TCP_PORT
                  value: "3306"
                - name: MYSQL_PORT_3306_TCP_ADDR
                  value: 127.0.0.1
                - name: MYSQL_USER
                  value: root
                - name: MYSQL_PASSWORD
                  value: password
                - name: MYSQL_DATABASE
                  value: drupal
                ports:
                - containerPort: 80
            restartPolicy: Always

  - name: Create Drupal Service
    kubernetes:
      endpoint: "{{ apiserver_endpoint }}"
      state: present
      model:
        apiVersion: v1
        kind: Service
        metadata:
          name: "{{ application_name }}"
          namespace: default
          labels:
            app: "{{ application_name }}"
        spec:
          type: NodePort
          ports:
          - port: 8080
            targetPort: 80
            protocol: TCP
          selector:
            app: "{{ application_name }}"
    register: service_resp
    
  - name: Update the stored cluster app configuration.
    kube_cluster_app_patch:
      endpoint: "{{ services_endpoint }}"
      authorization: "{{ authorization }}"
      account_alias: "{{ account_alias }}"
      cluster_id: "{{ cluster_id }}"
      cluster_app_id: "{{ cluster_app_id }}"
      patch:
        port: "{{ service_resp.content.spec.ports[0].nodePort }}"
        state: "ready"
        installation: 100