- name: Add glusterfs epl repository.
  template: src=glusterfs-rhelsa.repo.j2 dest=/etc/yum.repos.d/glusterfs-rhelsa.repo
  
- name: Install glusterfs packages
  yum: name={{item}} state=present
  with_items:
    - glusterfs
    - glusterfs-cli
    - glusterfs-server
    - glusterfs-fuse
    - glusterfs-geo-replication
    
- name: Gluster is running as a service
  service: name=glusterd state=started enabled=yes